### PR TITLE
Feature/tasks project auction

### PR DESCRIPTION
**Pull request by gabumoh**
Project Auction Feature completed

### CODE REVIEW

**Comment by xyluz** [comment]
capture

What i see when i login as a user @gabumoh

**Comment by gabumoh** [comment]
Did you run migrations? @xyluz

**Comment by xyluz** [comment]
@gabumoh after bid is awarded to me, i should not be able to edit my bid again... since i already got the job.

**Comment by gabumoh** [comment]
@xyluz there should be a logic for this, but I would re-implement it. Because once the bid is closed (which is automatically done once the task is assigned) no user should be able to edit any bid on said task, but still I would look into why you can still edit the bid.

**Comment by xyluz** [comment]
@gabumoh i have fixed it.

**Pull request merged**
