### PR TITLE
Feature/remake migrations

### PR DESCRIPTION
**Pull request by wisdomanthoni**

### CODE REVIEW

**Comment by xyluz** [comment]
@wisdomanthoni don't close issues please

**Comment by xyluz** [comment]
Please write tests for this

**Comment by wisdomanthoni** [comment]
@xyluz dunno this should be closed as this feature is way out of track ... Maybe we can revisit it again as the last thing.

**Comment by xyluz** [comment]
@wisdomanthoni actually, this is the right time to do this. We are done with the major features.

**Comment by wisdomanthoni** [comment]
Yippee ... Ok I'll work on this so everyone can test

**Pull request closed without merging**
